package fr.mxyns.rpc.example;

/*
 * This is a dummy class created so that the IDE doesn't detect errors when using the class
 * This class will be ignored and replaced by the one that will be generated by the Compiler
 * We do not care about the content of the methods. It will be generated by the compiler.
 */
public class Voiture implements IVoiture {

    public String name = "";

    @Override
    public String name() { return null; }

    @Override
    public void name(String newName) { }

    @Override
    public Trajet rouleChezToi(String str) { return null; }

    @Override
    public Trajet roule(String from, String to) { return null; }

    @Override
    public String reversedName(String prefix, String suffix) { return null; }

    @Override
    public String toString() { return null; }
}
